version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
  
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDINGS_SERVICE_URL=http://embeddings-service:8001

    depends_on:
      - qdrant
      - embeddings-service

  ui:
    build: ./ui
    ports:
      - "8003:8003"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api

  embeddings-service:
    build: ./embeddings-service
    ports:
      - "8001:8001"


volumes:
  qdrant_storage: